name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 24.1.0
        uses: actions/setup-node@v4
        with:
          node-version: '24.1.0'
          cache: 'npm'

      # Schritt 3: Node.js-Abhängigkeiten installieren
      # WICHTIG: 'npm ci --ignore-scripts' wird das Husky-Problem beheben.
      - name: Install dependencies
        run: npm ci --ignore-scripts # <-- HIER IST DIE KRITISCHE ÄNDERUNG!

      - name: Build Angular application
        run: npm run build # Dieser Schritt wird immer noch normal ausgeführt

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_SEA_09AE0D803 }}
          action: 'upload'
          app_location: 'dist/angular-project-janos-imhof/browser'
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_SEA_09AE0D803 }}
          action: 'close'
          app_location: '/'
